### ISSUE TITLE
Uncaught TypeError: Cannot read properties of undefined (reading 'wallets')

### ISSUE THREAD

**Issue by ossiHQ** [lorisleiva/solana-wallets-vue#21]
### What i want to debug

```
import { walletOptions } from "./../main.js"
import { useWallet } from 'solana-wallets-vue';
import { initWallet } from 'solana-wallets-vue';
initWallet(walletOptions);

console.log(useWallet().connected)
```

The error message: ```Uncaught TypeError: Cannot read properties of undefined (reading 'wallets')
    at createWalletStore (solana-wallets-vue.es.js?313d:417:1)
    at initWallet (solana-wallets-vue.es.js?313d:591:1)```

**Comment by lucalaneth** [comment]
@ossiHQ  try useWallet().value.connected?

**Comment by Tilakraj0308** [comment]
@ossiHQ @lucalaneth Can any of you provide me any details or progress  regarding this topic? I am getting error like:
idl.ts:126  Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'kind')
    at IdlCoder.typeDefLayout (idl.ts:126:1)
    at eval (accounts.ts:38:1)
    at Array.map (<anonymous>)
    at new BorshAccountsCoder (accounts.ts:37:1)
    at new BorshCoder (index.ts:48:1)
    at new Program (index.ts:290:1)
    at eval (VM6663 useWorkspace.js:64:71)
    at ReactiveEffect.eval [as fn] (reactivity.esm-bundler.js:987:1)
    at ReactiveEffect.run (reactivity.esm-bundler.js:177:1)
    at get value (reactivity.esm-bundler.js:1000:1)
