### ISSUE TITLE
Production build fails with Vue + Vite

### ISSUE THREAD

**Issue by 0x62** [lorisleiva/solana-wallets-vue#37]
I'm trying to add this to my Vue + Vite project. Everything works great in dev mode, but when I try to build for production it fails with the error:

```
✓ 3521 modules transformed.
[vite-plugin-pwa:build] 'serialize' is not exported by node_modules/borsh/lib/index.js, imported by node_modules/@solana/web3.js/lib/index.browser.esm.js
file: /Users/benlewis/dhh/nftinator/node_modules/@solana/web3.js/lib/index.browser.esm.js:7:9
5: import bs58 from 'bs58';
6: import { sha256 } from '@noble/hashes/sha256';
7: import { serialize, deserialize, deserializeUnchecked } from 'borsh';
            ^
8: import * as BufferLayout from '@solana/buffer-layout';
9: import { blob } from '@solana/buffer-layout';
error during build:
Error: 'serialize' is not exported by node_modules/borsh/lib/index.js, imported by node_modules/@solana/web3.js/lib/index.browser.esm.js
    at error (file:///Users/benlewis/dhh/nftinator/node_modules/vite/node_modules/rollup/dist/es/shared/rollup.js:1858:30)
    at Module.error (file:///Users/benlewis/dhh/nftinator/node_modules/vite/node_modules/rollup/dist/es/shared/rollup.js:12429:16)
    at Module.traceVariable (file:///Users/benlewis/dhh/nftinator/node_modules/vite/node_modules/rollup/dist/es/shared/rollup.js:12788:29)
    at ModuleScope.findVariable (file:///Users/benlewis/dhh/nftinator/node_modules/vite/node_modules/rollup/dist/es/shared/rollup.js:11440:39)
    at ChildScope.findVariable (file:///Users/benlewis/dhh/nftinator/node_modules/vite/node_modules/rollup/dist/es/shared/rollup.js:6372:38)
    at ClassBodyScope.findVariable (file:///Users/benlewis/dhh/nftinator/node_modules/vite/node_modules/rollup/dist/es/shared/rollup.js:6372:38)
    at ChildScope.findVariable (file:///Users/benlewis/dhh/nftinator/node_modules/vite/node_modules/rollup/dist/es/shared/rollup.js:6372:38)
    at FunctionScope.findVariable (file:///Users/benlewis/dhh/nftinator/node_modules/vite/node_modules/rollup/dist/es/shared/rollup.js:6372:38)
    at ChildScope.findVariable (file:///Users/benlewis/dhh/nftinator/node_modules/vite/node_modules/rollup/dist/es/shared/rollup.js:6372:38)
    at Identifier.bind (file:///Users/benlewis/dhh/nftinator/node_modules/vite/node_modules/rollup/dist/es/shared/rollup.js:7439:40)
```

This is my `vite.config.js`:

```
import vue from '@vitejs/plugin-vue'
import inject from '@rollup/plugin-inject'

const config = {
  plugins: [
    vue(),
    inject({
      Buffer: ['buffer', 'Buffer']
    }),
  ],
  resolve: {
    alias: {
      '@': path.resolve(__dirname, './src'),
      '@ui': path.resolve(__dirname, './src/components/ui')
    },
  },
  define: {
    '__COMMIT_HASH__': JSON.stringify(commitHash),
    'process.env.NODE_DEBUG': JSON.stringify(""),
    'process.env.BROWSER': true,
  },
  // https://github.com/lorisleiva/solana-wallets-vue
  build: {
    sourcemap: true,
    target: 'esnext',
  },
  esbuild: {
    target: 'esnext',
  },
  optimizeDeps: {
    esbuildOptions: {
      target: 'esnext',
    },
    include: ['@project-serum/anchor', '@solana/web3.js', 'buffer'],
  },
  server: {
    port: 3000
  },
}
```

**Comment by 0x62** [comment]
Removing `inject()` plugin fixed it, but had to also replace native Buffer with `import { Buffer } from 'buffer'`
